services:
    db:
      image: postgres:15.3
      environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        postgres_DB: db_postgres_latihan
      volumes:
        - db_data:/var/lib/postgresql/data
      ports:
        - 5432:5432

volumes:
  db_data: